version: '3.8'

services:

  postgresdbService:
    container_name: postgres-containers
    image: postgres
    restart: always
    ports:
      - 5434:5432
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
        - ./src/dbseed:/docker-entrypoint-initdb.d

  deel-task:
    container_name: deel-container
    build: 
      context: src
      dockerfile: DockerFile
    restart: always
    env_file: ./.env
    ports:
      - 3000:3000    

volumes: 
  db: